version: "3.0"

services: 
    telegraf-1:
        image: telegraf:1.19
        restart: always
        container_name: telegraf-1
        hostname: telegraf-1
        ports: 
            - 9273:9273
        volumes: 
            - ./telegraf-1/telegraf.conf:/etc/telegraf/telegraf.conf
            - ./telegraf-1/telegraf.d/:/etc/telegraf/telegraf.d/
        command: telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d

    telegraf-2:
        image: telegraf:1.19
        restart: always
        container_name: telegraf-2
        hostname: telegraf-2
        ports: 
            - 9274:9274
        volumes: 
            - ./telegraf-2/telegraf.conf:/etc/telegraf/telegraf.conf
            - ./telegraf-2/telegraf.d/:/etc/telegraf/telegraf.d
        command: telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d

    prometheus:
        image: prom/prometheus:v2.28.1
        restart: always
        container_name: prometheus
        hostname: prometheus
        ports: 
            - 9090:9090
        volumes: 
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: --config.file=/etc/prometheus/prometheus.yml
 
    pushgateway:
        image: prom/pushgateway:v1.4.1
        restart: always
        container_name: pushgateway
        hostname: pushgateway
        ports: 
            - 9091:9091
    
    alertmanager:
        image: prom/alertmanager:v0.22.2
        restart: unless-stopped
        container_name: alertmanager
        hostname: alertmanager
        ports: 
            - 9093:9093

    grafana:
        image: grafana/grafana:8.1.0
        restart: unless-stopped
        container_name: grafana
        hostname: grafana
        ports: 
            - 3000:3000
        env_file: 
            - ./grafana/config.monitoring

    busybox:
        image: busybox:1.33.1
        restart: unless-stopped
        container_name: busybox
        hostname: busybox
        command: sh -c "while true; do sleep 3600; done"
