{
 "title": "CPU&Mem",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(host)" } },
   {
    "name": "url",
    "query": {
     "query": "ping_average_response_ms{host=\"$host\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$host - $url",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "url",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_average_response_ms{host=\"$host\", url=\"$url\"}",
     "legendFormat": "average"
    },
    {
     "expr": "ping_maximum_response_ms{host=\"$host\"}",
     "legendFormat": "maximum"
    },
    {
     "expr": "ping_minimum_response_ms{host=\"$host\"}",
     "legendFormat": "minimum"
    }
   ]
  },
  {
   "title": "CPU&Total",
   "type": "stat",
   "description": "show instant cpu",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\", host=\"telegraf-1\"}*100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "description": "instant cpu used.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_user{cpu!=\"cpu-total\", host=\"telegraf-1\"}*100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU&moive",
   "type": "gauge",
   "description": "show cpu instant",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_user{host=\"telegraf-1\", cpu=\"cpu0\"}*100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "URL&",
   "type": "table",
   "description": "ping table url",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_average_response_ms{url=\"baidu.com\", host=\"telegraf-1\"}"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"baidu.com\", host=\"telegraf-1\"}"
    },
    {
     "expr": "ping_minimum_response_ms{url=\"baidu.com\", host=\"telegraf-1\"}"
    }
   ]
  }
 ]
}